<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ts-axios examples</title>
  <link rel="stylesheet" href="/global.css">
</head>

<body>
  <h1>ts-axios examples</h1>
  <ul>
    <li><a href="simple">Simple</a></li>
    <li><a href="base">Base</a></li>
    <li><a href="error">Error</a></li>
    <li><a href="extend">Extend</a></li>
    <li><a href="interceptor">Interceptor</a></li>
    <li><a href="config">Config</a></li>
    <li><a href="cancel">Caccel</a></li>
    <li><a href="more">More</a></li>
    <li><a href="upload-download">Upload</a></li>
  </ul>



  <!-- <script>

    var promise = new Promise(function (resolve, reject) {
      // setTimeout(function () {
        throw 'Uncaught Exception!';
      // }, 1000);
    });

    promise.catch(function (e) {
      console.log(111)
      console.log(e);       //This is never called
    });

  </script> -->

  <!-- <script>
使用then方法之后会返回一个promise对象，可以继续用then方法调用
，再次调用所获取的参数是上个then方法return的内容,上一个then没有返回值则是 undefined
return Promise.resolve('hello')  === return 'hello'

    function demo1() {
      return new Promise((resolve, reject) => {
        resolve({ type: 'resolve' });
        // reject({ type: 'reject' });
      })
    }

    function demo2() {
      return demo1()
        .then((res) => {
          console.log(1)
          res.name = 'jack'
          return res;
        })
        .then(res => {
          console.log(2)
          res.age = '24'
          return res
        })
      // 一旦捕捉后面的 catch 就捕捉不到了
      // .catch(err => {
      //   console.log(3)
      //   err.age = '23'
      //   return err
      // })
    }

    function demo3() {
      return demo2()
    }

    demo2()
      .then(res => {
        console.log(res)
      })
      .catch(err => {
        console.log(err)
      })

    console.log(demo2())

    demo3()
      .then(res => {
        console.log(4)
        console.log(res)
      })
      .catch(err => {
        console.log(5)
        console.log(err)
      })

  </script> -->

  <script>
    // 拦截器管理
    function InterceptorManager() {
      this.interceptors = []
    }
    InterceptorManager.prototype.use = function (resolved, rejected) {
      this.interceptors.push({ resolved, rejected });
      return this.interceptors.length - 1
    }

    InterceptorManager.prototype.eject = function (index) {
      if (this.interceptors[index]) {
        this.interceptors[index] = null;
      }
    }
    InterceptorManager.prototype.loop = function (fn) {
      this.interceptors.forEach(interceptor => {
        if (interceptor) {
          fn(interceptor);
        }
      })
    }

    let manager = {
      request: new InterceptorManager(),
      response: new InterceptorManager()
    }

    manager.request.use(
      function resolved(res) {
        console.log(1, res)
        console.log('===================')
        return res
      },
      function rejected(err) {
        console.log(11, err)
        console.log('===================')
        return Promise.reject(err)
      }
    )

    manager.request.use(
      function resolved(res) {
        console.log(2, res)
        console.log('===================')
        return res
      },
      function rejected(err) {
        console.log(22, err)
        console.log('===================')
        return Promise.reject(err)
      }
    )


    manager.response.use(
      function resolved(res) {
        console.log(3, res)
        console.log('===================')
        return res
      },
      function rejected(err) {
        console.log(33, err)
        console.log('===================')
        return Promise.reject(err)
      }
    )
    manager.response.use(
      function resolved(res) {
        console.log(4, res)
        console.log('===================')
        return res
      },
      function rejected(err) {
        console.log(44, err)
        console.log('===================')
        return err
        // return Promise.reject(err)
      }
    )



    let config = {
      name: 'jack',
      age: 23
    }

    function dispatchRequest(config) {
      console.log('1-1')
      // return Promise.resolve(config)
      return Promise.reject(config)
    }

    function start() {
      // 链
      let chain = [{
        resolved: dispatchRequest,
        rejected: undefined
      }]

      manager.request.loop(interceptor => {
        chain.unshift(interceptor)
      })
      manager.response.loop(interceptor => {
        chain.push(interceptor)
      })

      let promise = Promise.resolve(config);
      // debugger
      while (chain.length) {
        const { resolved, rejected } = chain.shift();
        promise = promise.then(resolved, rejected);
      }
      return promise;
    }


    start()
      .then(res => {
        console.log('then')
        console.log(res)
      })
      .catch(err => {
        console.log('catch')
        console.log(err)
      })

  </script>

</body>

</html>