<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ts-axios examples</title>
  <link rel="stylesheet" href="/global.css">
</head>

<body>
  <h1>ts-axios examples</h1>
  <ul>
    <li><a href="simple">Simple</a></li>
    <li><a href="base">Base</a></li>
    <li><a href="error">Error</a></li>
    <li><a href="extend">Extend</a></li>
    <li><a href="interceptor">Interceptor</a></li>
    <li><a href="config">Config</a></li>
    <li><a href="cancel">Caccel</a></li>
    <li><a href="more">More</a></li>
    <li><a href="upload-download">Upload</a></li>
  </ul>



  <script>

    function demo1() {
      return new Promise((resolve, reject) => {
        resolve({ type: 'resolve' });
        // reject({ type: 'reject' });
      })
    }

    function demo2() {
      return demo1()
        .then((res) => {
          console.log(1)
          res.name = 'jack'
          return res;
        })
      .then(res => {
        console.log(2)
        res.age = '24'
        return res
      })
      // 一旦捕捉后面的 catch 就捕捉不到了
      // .catch(err => {
      //   console.log(3)
      //   err.age = '23'
      //   return err
      // })
    }

    function demo3() {
      return demo2()
    }

    // demo2()
    //   .then(res => {
    //     console.log(res)
    //   })
    //   .catch(err => {
    //     console.log(err)
    //   })

    console.log(demo2())
    
    demo3()
      .then(res => {
        console.log(4)
        console.log(res)
      })
      .catch(err => {
        console.log(5)
        console.log(err)
      })


  </script>

</body>

</html>